services:
  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  react:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5713:5713"

  db:
    image: postgres:16.4
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=Rise_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aminkhm
    volumes:
      - Rise_db-data:/var/lib/postgresql/data

volumes:
  Rise_db-data: