# Generated by Django 5.1.2 on 2025-02-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_customuser_username_alter_customer_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CP', 'Customer project'), ('IP', 'Internal project')], default='Customer project', max_length=30)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.customer')),
                ('tags', models.ManyToManyField(to='projects.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4'), (5, 'level 5')], default=1, null=True)),
                ('stage', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('TODO', 'todo'), ('ONGOING', 'ongoing'), ('COMPLETED', 'completed'), ('CEO_APPROVED', 'CEO approved')], default='TODO', max_length=20, null=True)),
                ('priority', models.CharField(blank=True, choices=[('LESS', 'less priority'), ('HIGH', 'high priority'), ('NECESSARY', 'necessary'), ('VITAL', 'vital')], max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='task_files/')),
                ('attribution_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='accounts.customer')),
                ('contributor', models.ManyToManyField(blank=True, related_name='contributions', to='accounts.customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('tags', models.ManyToManyField(blank=True, to='projects.tags')),
            ],
        ),
    ]
